#! /usr/bin/env bash
#IHasFeet 2020
#This script will update the current OS and packages, before next stages begin.
#This set of commands will setup the below packages, which are common across all profiles
#		ranger
#		screen
#		nnn
#		snap
#		make
#		python-pip
#
#Execute by running the below command
#sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/ScriptHousekeeping/startscript -O ~/startscript && bash startscript
#
#You can run this file multiple times without causing issues.
#Perhaps run it twice if your OS hasn't been upgraded for a while?
#
#                                                                                                                                                  
echo IHaveFeet  IHaveFeet
#
echo So let me walk you through this...
echo setupstartscript_001 >> ~/setup.log
#
#Firstly, we will replace the AU version of sources.list with the generic.  It may be a little slower, but it's proven to be more reliable in terms of DNS lookups
sudo mv /etc/apt/sources.list /etc/apt/sources.list.bak
sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/ScriptHousekeeping/sources.list -O /etc/apt/sources.list
echo setupstartscript_002 >> ~/setup.log
#
#Now we must update...
#
sudo apt-get update
echo setupstartscript_003 >> ~/setup.log
sudo apt-get upgrade -y
echo setupstartscript_004 >> ~/setup.log
sudo do-release-upgrade
echo setupstartscript_005 >> ~/setup.log
sudo apt-get install ranger screen nnn snap snapd make python-pip -y
echo setupstartscript_006 >> ~/setup.log
sudo service snapd start
echo setupstartscript_007 >> ~/setup.log


