#! /usr/bin/env bash
#IHasFeet 2020
#This script will update the current OS and packages, before next stages begin.
#
#Execute by running the below command
#sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/setupall -O ~/setupall && bash ~/setupall
#
#You can run this file multiple times without causing issues.
#Perhaps run it twice if your OS hasn't been upgraded for a while?
#
#The primary use of this file is to call the scripts directly, without the constant apt-get update etc.
#You will see the scripts called below are not any of the ones ending in only (e.g. setupdesktoponly)
#Call the start script
echo "STARTING RUN..." >> ~/setup.log
echo `date` >> ~/setup.log
echo setupall_001 >> ~/setup.log
sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/ScriptHousekeeping/startscript -O ~/startscript
sudo chmod +x ~/startscript
sudo ~/startscript
echo setupall_002 >> ~/setup.log
#Call the scripts
sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/desktop/setupdesktop -O ~/setupdesktop
sudo chmod +x ~/setupdesktop
~/setupdesktop
echo setupall_003 >> ~/setup.log
sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/pentesttools/setuppentesttools -O ~/setuppentesttools
sudo chmod +x ~/setuppentesttools
~/setuppentesttools
echo setupall_004 >> ~/setup.log
sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/setup_OpenVAS/setupopenvas -O ~/setupopenvas
sudo chmod +x ~/setupopenvas
~/setupopenvas
echo setupall_005 >> ~/setup.log
sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/SonarQube/setupsonarqube -O ~/setupsonarqube
sudo chmod +x ~/setupsonarqube
~/setupsonarqube
echo setupall_006 >> ~/setup.log
sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/dev/setupdev -O ~/setupdev
sudo chmod +x ~/setupdev
~/setupdev
echo setupall_006a >> ~/setup.log
#Call finish script
sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/ScriptHousekeeping/finishscript -O ~/finishscript
sudo chmod +x ~/finishscript
~/finishscript
echo setupall_007 >> ~/setup.log
echo "FINISHING RUN..." >> ~/setup.log
echo `date` >> ~/setup.log

#
#
