#! /usr/bin/env bash
#IHasFeet 2020
#This script will update the current OS and packages, before next stages begin.
#
#Execute by running the below command
#sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/setupdesktoponly -O ~/setupdesktoponly && bash ~/setupdesktoponly
#
#You can run this file multiple times without causing issues.
#Perhaps run it twice if your OS hasn't been upgraded for a while?
#
#Call the start script
echo setupdesktoponly_001 >> ~/setup.log
echo Calling startup script
sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/ScriptHousekeeping/startscript -O ~/startscript && bash ~/startscript
echo setupdesktoponly_002 >> ~/setup.log
#Call the desktop script
echo Calling desktop script
sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/desktop/setupdesktop -O ~/setupdesktop && bash ~/setupdesktop
echo setupdesktoponly_003 >> ~/setup.log
#Call finish script
echo Calling finish script
sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/ScriptHousekeeping/finishscript -O ~/finishscript && bash ~/finishscript
echo setupdesktoponly_004 >> ~/setup.log
#

