#! /usr/bin/env bash
#IHasFeet 2020
#This set of commands will setup 
#		i3
#		xRDP
#		Firefox
#		LibreOffice
#		Onedrive
#The aim is to take you from an Ubuntu server to a remotely accessible GUI,
#suitable to run basic desktop functionalalities
#
#xRDP will allow you to use multiple monitors if that is your client configuration.
#
#Execute by running the below command
#sudo wget https://raw.githubusercontent.com/IHasFeet/Configs/master/desktop/setupdesktop -O ~/setupdesktop && bash setupdesktop
#
#You can run this file multiple times without causing issues.
#Perhaps run it twice if your OS hasn't been upgraded for a while?
#
#
#We install firefox separately, as Kali doesn't find an installation candidate by default, which fails the whole line.
#
echo setupdesktop_001 >> ~/setup.log
sudo apt-get install i3 xrdp  conky onedrive feh w3m-img imagemagick -y
echo setupdesktop_002 >> ~/setup.log
sudo apt-get install firefox -y
echo setupdesktop_003 >> ~/setup.log
sudo snap install libreoffice
echo setupdesktop_004 >> ~/setup.log
sudo service xrdp start
echo setupdesktop_005 >> ~/setup.log
#
mkdir ~/.config
mkdir ~/.config/i3
echo setupdesktop_006 >> ~/setup.log
wget https://raw.githubusercontent.com/IHasFeet/Configs/master/i3/config -O ~/.config/i3/config
echo setupdesktop_007 >> ~/setup.log
echo i3 > ~/.xsession
